<?php

// Include the entity class
module_load_include('inc', 'organization', 'organization.entity');
function organization_menu()
{

    $items = array();

    $items['organization'] = array(
        'title' => t('Organization'),
        'page callback' => 'organization_list_page',
        'access callback' => TRUE,
        'access arguments' => array('access content'),
    );

    $items['organization/add'] = array(
        'title' => t('Add Organization'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('organization_form'),
        'access arguments' => array('access content'),
    );

    $items['organization/edit/%'] = array(
        'title' => t('Edit Organization'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('organization_form', 2),
        'access arguments' => array('access content'),

    );

    $items['organization/delete/%'] = array(
        'title' => t('Delete Organization'),
        'page callback' => 'organization_delete',
        'page arguments' => array(2),
        'access arguments' => array('administer site configuration'),
    );

    $items['organization/view/%'] = array(
        'title' => t('View Organization'),
        'page callback' => 'organization_view',
        'page arguments' => array(2),
        'access arguments' => array('access content'),
    );

    return $items;
}

/*
 * Organization Entity definition
 */

function organization_entity_info()
{
    $return['organization'] = array(
        'label' => t('Organization'),
        'base table' => 'organization',
        'controller class' => 'OrganizationAPIController',
        'fieldable' => TRUE,
        'entity keys' => array(
            'id' => 'id',
            'bundle' => 'type',
        ),
        'bundle keys' => array(
            'bundle' => 'type',
        ),
        'bundles' => array(
            'organization' => array(
                'label' => t('Organization'),
            ),
        ),
        'module' => 'organization',
    );

    return $return;
}

function organizationController(): OrganizationAPIController
{
    return new OrganizationAPIController('organization');
}

function entityWrapper($org)
{
    $wrapper = entity_metadata_wrapper('organization', $org);

    $id = NULL;
    if (!empty($wrapper->id->value())) {
        $id = $wrapper->id->value();
    }


    $name = $wrapper->name->value();
    $status = $wrapper->status->value();

    // Manager
    $manager_name = '';
    try {
        $manager = $wrapper->field_custom_manager->value();
        if ($manager) {
            $manager_name = $manager->name;
        }
    } catch (Exception $e) {
        $manager_name = '';
    }

    // Phone
    $phone = '';
    try {
        $phone = $wrapper->field_custom_phone->value();
    } catch (Exception $e) {
        $phone = '';
    }

    // Address
    $address = '';
    try {
        $address = $wrapper->field_custom_address->value();
    } catch (Exception $e) {
        $address = '';
    }

    $logo = '';
    try {
        $logo = $wrapper->field_custom_logo->value();
    } catch (Exception $e) {
        $logo = '';
    }

    return array(
        'id' => $id,
        'name' => $name,
        'status' => $status,
        'manager_name' => $manager_name,
        'phone' => $phone,
        'address' => $address,
        'logo' => $logo,
    );
}

function organization_list_page()
{
    $header = array(t('Id'), t('Organization Name'), t('Address'), t('Manager'), t('Phone'), t('Operations'));

    $rows = array();
    // loads all organizations
    $organizations = organizationController()->loadOrganization();
    foreach ($organizations as $org) {
        $wrapperResult = entityWrapper($org);

        $links = array();
        $links = array(
            'view' => array(
                'title' => t('View'),
                'href' => 'organization/view/' . $org->id,
            ),
            'edit' => array(
                'title' => t('Edit'),
                'href' => 'organization/edit/' . $org->id,
            ),
            'delete' => array(
                'title' => t('Delete'),
                'href' => 'organization/delete/' . $org->id,
            ),
        );
        // Add row to the table
        $rows[] = array(
            $org->id,
            $org->name,
            $wrapperResult['address'],
            $wrapperResult['manager_name'],
            $wrapperResult['phone'],
            array(
                'data' => theme('links__ctools_dropbutton', array(
                    'links' => $links,
                    'attributes' => array('class' => array('links', 'inline')),
                )),
            ),
        );
    }

    $build['table'] = array(
        '#theme' => 'table',
        '#header' => $header,
        '#rows' => $rows,
        '#empty' => t('No organizations found'),
    );

    $build['pager'] = array(
        '#theme' => 'pager',
    );

    return $build;
}


function organization_form($form, &$form_state, $id = NULL)
{
    $organization = NULL;

    if ($id) {
        $organizationEntity = organizationController()->loadOrganizationByID($id);
        $organization = entityWrapper($organizationEntity);
//        var_dump($organization);
    }

    $form['id'] = array(
        '#type' => 'hidden',
        '#value' => $organization ? $organization['id'] : '',);

    $form['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Organization Name'),
        '#required' => TRUE,
        '#default_value' => $organization ? $organization['name'] : '',);

    $form['user'] = array(
        '#type' => 'textfield',
        '#title' => t('User'),
        '#autocomplete_path' => 'user/autocomplete',
        '#description' => t('Start typing the username.'),
        '#default_value' => $organization ? $organization['manager_name'] : '',);

    $form['status'] = array(
        '#type' => 'select',
        '#title' => t('Status'),
        '#options' => array(
            0 => t('Inactive'),
            1 => t('Active'),
        ),
        '#default_value' => $organization ? $organization['status'] : 0,);

    $form['address'] = array(
        '#type' => 'textarea',
        '#title' => t('Address'),
        '#default_value' => $organization ? $organization['address'] : '',
    );

    $form['phone'] = array(
        '#type' => 'textfield',
        '#title' => t('Phone'),
        '#default_value' => $organization ? $organization['phone'] : '',
    );

    $form['logo'] = array(
        '#type' => 'managed_file',
        '#title' => t('Logo'),
        '#upload_location' => 'public://organization_logos/',
        '#default_value' => $organization ? $organization['logo'] : '',
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Save Organization'),
    );

    return $form;
}

function organization_form_submit($form, &$form_state)
{

    $values = $form_state['values'];

    // Use entity_get_controller to create the object properly
    $controller = entity_get_controller('organization');
    $entity = $controller->create(array('type' => 'organization'));

    $lang = LANGUAGE_NONE;

    //for edit form
    $id = $form_state['values']['id'];

    // Base table properties
    $entity->name = $values['name'];
    $entity->status = $values['status'];

    //loads user
    $user = user_load_by_name($values['user']);

    $entity->field_custom_manager[$lang][0]['target_id'] = $user->uid;
    $entity->field_custom_address[$lang][0]['value'] = $values['address'];
    $entity->field_custom_phone[$lang][0]['value'] = $values['phone'];

    // File field handling
    if (!empty($values['logo'])) {
        $fid = is_array($values['logo']) ? $values['logo'][0] : $values['logo'];

        if ($file = file_load($fid)) {
            // Make the file permanent
            $file->status = FILE_STATUS_PERMANENT;
            file_save($file);

            $lang = LANGUAGE_NONE;

            $entity->field_custom_logo[$lang][0] = array(
                'fid' => $values['logo'],
                'display' => 1,
                'description' => '',
            );

            // Critical: Record that this entity is using this file
            file_usage_add($file, 'your_module', 'organization', $fid);
        }
    }

    if (!empty($id)) {
        $organization = organizationController()->loadOrganizationById($id);
        $organization->name = $values['name'];
        $organization->status = $values['status'];
        $organization->field_custom_manager[$lang][0]['target_id'] = $user->uid;
        $organization->field_custom_address[$lang][0]['value'] = $values['address'];
        $organization->field_custom_phone[$lang][0]['value'] = $values['phone'];


        organizationController()->saveOrganization($organization);
        drupal_set_message(t('Organization %name updated.', array('%name' => $entity->name)));

    } else {
        organizationController()->saveOrganization($entity);
        drupal_set_message(t('Organization %name saved.', array('%name' => $entity->name)));
    }
}


function organization_delete($id)
{
    organizationController()->deleteOrganization($id);
    drupal_set_message('Organization deleted.');
    drupal_goto('organization/list');
}

function organization_view($id)
{
    $organizationEntity = organizationController()->loadOrganizationByID($id);
    $wrappedOrganization = entityWrapper($organizationEntity);
    drupal_add_css(drupal_get_path('module', 'organization') . '/css/organization-view.css');
    return [
        '#theme' => 'organization_view',
        '#organization' => $wrappedOrganization,
    ];
}

function organization_theme($existing, $type, $theme, $path)
{
    return array(
//        'organization_list' => array(
//            'variables' => array(
//                'header' => NULL,
//                'rows' => NULL,
//                'empty' => NULL,
//            ),
//            'template' => 'organization-list',
//            'path' => drupal_get_path('module', 'organization') . '/templates',
//        ),
        'organization_view' => array(
            'variables' => array(
                'organization' => NULL,
            ),
            'template' => 'organization-view',
            'path' => drupal_get_path('module', 'organization') . '/templates',
        ),
    );
}