<?php

module_load_include('inc', 'asset', 'asset.entity');

function asset_menu()
{
    $items = [];

    $items['asset'] = array(
        'title' => t('Asset'),
        'page callback' => 'asset_list_page',
        'access callback' => TRUE,
        'access arguments' => array('view organization'),
    );

    $items['asset/add'] = array(
        'title' => t('Add Asset'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('asset_form'),
        'access arguments' => array('add asset'),
        'access callback' => 'asset_add_access',
    );

    $items['asset/edit/%'] = array(
        'title' => t('Edit Asset'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('asset_form', 2),
        'access callback' => 'asset_edit_access',
        'access arguments' => array(2),

    );

    $items['asset/delete/%'] = array(
        'title' => t('Delete Asset'),
        'page callback' => 'asset_delete',
        'page arguments' => array(2),
        'access arguments' => array(2),
        'access callback' => 'asset_delete_access',

    );

    $items['asset/view/%'] = array(
        'title' => t('View Asset'),
        'page callback' => 'asset_view',
        'page arguments' => array(2),
        'access arguments' => array(2),
        'access callback' => 'asset_view_access',);

    $items['organization/autocomplete'] = array(
        'page callback' => 'organization_autocomplete',
        'access arguments' => array('access content'), // or a custom permission
        'type' => MENU_CALLBACK,
    );

    $items['asset/maintenance/%'] = array(
        'title' => t('Asset Maintenance'),
        'page callback' => 'asset_maintenance',
        'page arguments' => array(2),
        'access arguments' => array('access content'),
    );

    return $items;
}

function asset_edit_access($id)
{

    global $user;

    // Admin can always edit
    if (user_access('administer site configuration')) {
        return TRUE;
    }

    return assetAccessQuery($id);
}

function asset_view_access($id)
{
    global $user;

    // Admin can always edit
    if (user_access('administer site configuration')) {
        return TRUE;
    }

    // Load the asset
    return assetAccessQuery($id);
}

function asset_delete_access($id)
{
    global $user;

    // Admin can always edit
    if (user_access('administer site configuration')) {
        return TRUE;
    }
    return assetAccessQuery($id);
}

function asset_add_access()
{
    global $user;

    // Admin can always edit
    if (user_access('administer site configuration')) {
        return TRUE;
    }
    return FALSE;
}

function assetAccessQuery($id): bool
{
    global $user;
    $query = db_select('asset', 'a')
        ->fields('a', ['id'])
        ->condition('a.id', $id);
    $query->join('field_data_field_custom_asset_organization', 'fco', "fco.entity_id = a.id");
    $query->join('organization', 'o', 'o.id = fco.field_custom_asset_organization_target_id');
    $query->join('field_data_field_custom_manager', 'fcm', 'fcm.entity_id = o.id');
    $query->condition('fcm.field_custom_manager_target_id', $user->uid);
    $result = $query->execute()->fetchField();
    return ((bool)$result);
}

/**
 * Asset Entity definition
 */
function asset_entity_info()
{
    $return['asset'] = array(
        'label' => t('Asset'),
        'base table' => 'asset',
        'controller class' => 'AssetAPIController',
        'fieldable' => TRUE, //needs to be true to save data to fields
        'entity keys' => array(
            'id' => 'id',

        ),
        'bundle keys' => array(
            'bundle' => 'type',
        ),
        'bundles' => array(
            'asset' => array(
                'label' => t('Asset'),
            ),
        ),
        'module' => 'asset',
    );

    return $return;
}

function assetController(): AssetAPIController
{
    return new AssetAPIController('asset');
}

function assetEntityWrapper($asset)
{
    $wrapper = entity_metadata_wrapper('asset', $asset);

    $id = NULL;
    if (!empty($wrapper->id->value())) {
        $id = $wrapper->id->value();
    }


    $name = $wrapper->name->value();
    $ssn = $wrapper->ssn->value();

    $asset_type = '';
    try {
        $term = $wrapper->field_custom_asset_type->value();
        if ($term) {
            $asset_type = $term->name;
        }
    } catch (Exception $e) {
        $asset_type = '';
    }

// asset_condition
    $asset_condition = '';
    try {
        $term = $wrapper->field_custom_asset_condition->value();
        if ($term) {
            $asset_condition = $term->name;
        }
    } catch (Exception $e) {
        $asset_condition = '';
    }

    // asset_organization
    $asset_organization = '';
    try {
        $organization = $wrapper->field_custom_asset_organization->value();
        if ($organization) {
            $asset_organization = $organization->name;
        }
    } catch (Exception $e) {
        $asset_organization = '';
    }

    // user
    $assigned_user = '';
    try {
        $user = $wrapper->field_custom_assigned_user->value();
        if ($user) {
            $assigned_user = $user->name;
        }
    } catch (Exception $e) {
        $assigned_user = '';
    }

    $asset_image = '';
    try {
        $asset_image = $wrapper->field_custom_asset_image->value();
    } catch (Exception $e) {
        $asset_image = '';
    }

    return array(
        'id' => $id,
        'name' => $name,
        'ssn' => $ssn,
        'asset_type' => $asset_type,
        'asset_condition' => $asset_condition,
        'asset_organization' => $asset_organization,
        'assigned_user' => $assigned_user,
        'asset_image' => $asset_image,
    );
}

function asset_form($form, &$form_state, $id = NULL)
{
    $asset = NULL;
    if ($id) {
        $assetEntity = assetController()->loadAssetByID($id);
        $asset = assetEntityWrapper($assetEntity);
    }


    $form['id'] = array(
        '#type' => 'hidden',
        '#default_value' => isset($asset['id']) ? $asset['id'] : '',
    );

    $form['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Asset Name'),
        '#required' => TRUE,
        '#default_value' => isset($asset['name']) ? $asset['name'] : '',
    );

    $form['ssn'] = array(
        '#type' => 'textfield',
        '#title' => t('SSN'),
        '#required' => TRUE,
        '#default_value' => isset($asset['ssn']) ? $asset['ssn'] : '',
    );

    /**
     * TAXONOMY SELECTS
     */

    $taxonomy_options = asset_get_taxonomy_options('asset_type');
    if (!empty($id)) {
        $term_id = array_search($asset['asset_type'], $taxonomy_options);
    }
    // Asset Type
    $form['asset_type'] = array(
        '#type' => 'select',
        '#title' => t('Asset Type'),
        '#options' => $taxonomy_options,
        '#empty_option' => t('- Select Type -'),
        '#default_value' => isset($term_id) ? $term_id : '');

    $taxonomy_options = asset_get_taxonomy_options('asset_condition');
    if (!empty($id)) {
        $term_id = array_search($asset['asset_condition'], $taxonomy_options);
    }
    // Asset Condition
    $form['asset_condition'] = array(
        '#type' => 'select',
        '#title' => t('Asset Condition'),
        '#options' => asset_get_taxonomy_options('asset_condition'),
        '#empty_option' => t('- Select Condition -'),
        '#default_value' => isset($term_id) ? $term_id : '');

    /**
     * ENTITY AUTOCOMPLETE
     */

    // Organization
    $form['asset_organization'] = array(
        '#type' => 'textfield',
        '#title' => t('Organization'),
        '#autocomplete_path' => 'organization/autocomplete',
        '#default_value' => isset($asset['asset_organization']) ? $asset['asset_organization'] : '',
    );

    // Assigned User
    $form['assigned_user'] = array(
        '#type' => 'textfield',
        '#title' => t('Assigned User'),
        '#autocomplete_path' => 'user/autocomplete',
        '#default_value' => isset($asset['assigned_user']) ? $asset['assigned_user'] : '',
    );

    /**
     * IMAGE
     */

    $form['asset_image'] = array(
        '#type' => 'managed_file',
        '#title' => t('Asset Image'),
        '#upload_location' => 'public://asset_images/',
        '#default_value' => isset($asset['asset_image']) ? array($asset['asset_image']) : '',
    );

    /**
     * SUBMIT
     */

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Save Asset'),

    );

    $module_path = drupal_get_path('module', 'asset');

    $form['#attached']['js'][] = array(
        'data' => $module_path . '/js/jquery.validate.min.js',
        'type' => 'file',
        'scope' => 'header',
        'weight' => -20,
    );

    $form['#attached']['js'][] = array(
        'data' => $module_path . '/js/additional-methods.js',
        'type' => 'file',
        'scope' => 'header',
        'weight' => -19,
    );

    $form['#attached']['js'][] = array(
        'data' => $module_path . '/js/asset-form-validate.js',
        'type' => 'file',
        'scope' => 'header',
        'weight' => -18,
    );

    $form['#attributes']['id'] = 'asset-form';
    $form['#theme'] = 'asset_form_template';
    $form['#attached']['css'][] = drupal_get_path('module', 'asset') . '/css/asset-form.css';

    return $form;
}

//autocomplete
function organization_autocomplete($string)
{
    $matches = array();

    $string = trim(substr($string, 0, 255));
    $string = preg_replace('/[\x00-\x1F\x7F]/u', '', $string);
    $result = db_select('organization', 'o')
        ->fields('o', ['name'])
        ->condition('name', db_like($string) . '%', 'LIKE')
        ->range(0, 10)
        ->execute()
        ->fetchAll();
    foreach ($result as $row) {
        $matches[$row->name] = check_plain($row->name);
    }

    drupal_json_output($matches);
}

//filter form
function asset_filter($form, &$form_state)
{
    $params = drupal_get_query_parameters();
//    $form['search'] = array(
//        '#type' => 'textfield',
//        '#default_value' => isset($params['search']) ? $params['search'] : '',
//        '#attributes' => array('placeholder' => t('Search organizations...'), 'id' => 'table-search'),
//    );

    $taxonomy_options = asset_get_taxonomy_options('asset_condition');

    $form['status'] = array(
        '#type' => 'select',
        '#options' => $taxonomy_options,
        '#default_value' => isset($form['status']) ? $form['status'] : '',
        '#ajax' => array(
            'callback' => 'test_callback',
            'wrapper' => 'assets-wrapper',
        ),
    );

//    $build['#attached']['js'][] = drupal_get_path('module', 'asset') . '/js/filter-ajax.js';
    return $form;
}

//ajax callback
function test_callback($form, &$form_state)
{

    $selected_status = $form_state['values']['status'];
    $build['assets_wrapper'] = array(
        '#type' => 'container',
        '#attributes' => array('id' => 'assets-wrapper'),
    );
    $header = array(t('Id'), t('Name'), t('Asset Type'), t('Asset Condition'), t('Organization'), t('Assigned User'), t('Operations'));
    $assets = assetController()->loadAsset($selected_status);
    foreach ($assets as $asset) {
        $wrapperResult = assetEntityWrapper($asset);
        $links = array();

        $links = array(
            'view' => array(
                'title' => t('View'),
                'href' => 'asset/view/' . $asset->id,
            ),
            'edit' => array(
                'title' => t('Edit'),
                'href' => 'asset/edit/' . $asset->id,
            ),
            'delete' => array(
                'title' => t('Delete'),
                'href' => 'asset/delete/' . $asset->id,
                'attributes' => array(
                    'class' => array('use-ajax', 'delete-link'),
                    'data-org-id' => $asset->id, // optional, can use in JS
                ),
            ),
        );
        $rows[] = array(
            $asset->id,
            $asset->name,
            $wrapperResult['asset_type'],
            $wrapperResult['asset_condition'],
            $wrapperResult['asset_organization'],
            $wrapperResult['assigned_user'],
            $links
        );
    }


    $build['assets_wrapper']['table'] = array(
        '#theme' => 'asset_list',
        '#header' => $header,
        '#rows' => $rows,
        '#filter_form' => $form,
        '#empty' => t('No assets found'),
    );
    return $build;
}

//main list assets
function asset_list_page()
{
    $form = drupal_get_form('asset_filter');
//    $form = drupal_get_form('ajax_example_simplest');
    $build['assets_wrapper'] = array(
        '#type' => 'container',
        '#attributes' => array('id' => 'assets-wrapper'),
        '#prefix' => '<div id="assets-wrapper">',
        '#suffix' => '</div>',
    );


    $header = array(t('Id'), t('Name'), t('Asset Type'), t('Asset Condition'), t('Organization'), t('Assigned User'), t('Operations'));

    $assets = assetController()->loadAsset();
    foreach ($assets as $asset) {
        $wrapperResult = assetEntityWrapper($asset);
        $links = array();
        $links = array(
            'view' => array(
                'title' => t('View'),
                'href' => 'asset/view/' . $asset->id,
            ),
            'edit' => array(
                'title' => t('Edit'),
                'href' => 'asset/edit/' . $asset->id,
            ),
            'delete' => array(
                'title' => t('Delete'),
                'href' => 'asset/delete/' . $asset->id,
                'attributes' => array(
                    'class' => array('use-ajax', 'delete-link'),
                    'data-org-id' => $asset->id, // optional, can use in JS
                ),
            ),
        );
        $rows[] = array(
            $asset->id,
            $asset->name,
            $wrapperResult['asset_type'],
            $wrapperResult['asset_condition'],
            $wrapperResult['asset_organization'],
            $wrapperResult['assigned_user'],
            $links
        );
    }

    $build['assets_wrapper']['pager'] = array(
        '#theme' => 'pager',
    );
    $build['assets_wrapper']['table'] = array(
        '#theme' => 'asset_list',
        '#header' => $header,
        '#rows' => $rows,
        '#filter_form' => $form,
        '#empty' => t('No assets found'),
    );


    $build['#attached']['css'][] = drupal_get_path('module', 'asset') . '/css/asset-list.css';
    return $build;
}

function asset_form_validate($form, &$form_state)
{
    if (strlen(trim($form_state['values']['name'])) < 3) {
        form_set_error('name', t('Name must be at least 3 characters long.'));
    }
}

/**
 * @param $vocab_name
 * @return array
 */
function asset_get_taxonomy_options($vocab_name): array
{

    $options = array();
    $vocab = taxonomy_vocabulary_machine_name_load($vocab_name);

    if ($vocab) {
        $terms = taxonomy_get_tree($vocab->vid);

        foreach ($terms as $term) {
            $options[$term->tid] = $term->name;
        }
    }

    return $options;
}

function asset_query_asset_user_alter(QueryAlterableInterface $query)
{
    global $user;
    $query->join('field_data_field_custom_asset_organization', 'fao', 'fao.entity_id = asset.id');
    $query->join('organization', 'o', 'o.id = fao.field_custom_asset_organization_target_id');
    $query->join('field_data_field_custom_manager', 'fcm', 'fcm.entity_id = o.id');
    $query->condition('fcm.field_custom_manager_target_id', $user->uid);
}

function asset_form_submit($form, &$form_state)
{
    $values = $form_state['values'];
    $lang = LANGUAGE_NONE;
    $id = $values['id'];

    $user = user_load_by_name($values['assigned_user']);
    $organization_id = db_select('organization', 'o')
        ->fields('o', ['id'])
        ->condition('name', $values['asset_organization'])
        ->execute()
        ->fetchField();
    if (empty($organization_id)) {
        form_set_error('asset_organization', t('Invalid organization selected.'));
        return;
    }

    // gets entity controller for specified entity type
    if (!empty($id)) {
        $asset = assetController()->loadAssetByID($id);
        $asset->name = $values['name'];
        $asset->status = $values['status'];
        $asset->field_custom_asset_type[$lang][0]['tid'] = $values['asset_type'];
        $asset->field_custom_asset_condition[$lang][0]['tid'] = $values['asset_condition'];
        $asset->field_custom_asset_organization[$lang][0]['target_id'] = $organization_id;
        $asset->field_custom_assigned_user[$lang][0]['target_id'] = $user->uid;


        assetController()->saveAsset($asset);
        drupal_set_message(t('Asset %name updated.', array('%name' => $asset->name)));
        return;
    } else {
        $controller = entity_get_controller('asset');
        $entity = $controller->create(array('type' => 'asset'));

        $id = $form_state['values']['id'];
        $entity->name = $values['name'];
        $entity->ssn = $values['ssn'];

        $entity->field_custom_asset_type[$lang][0]['tid'] = $values['asset_type'];
        $entity->field_custom_asset_condition[$lang][0]['tid'] = $values['asset_condition'];
        $entity->field_custom_asset_organization[$lang][0]['target_id'] = $organization_id;
        $entity->field_custom_assigned_user[$lang][0]['target_id'] = $user->uid;

        //  Asset image
        if (!empty($values['asset_image'])) {
            $fid = is_array($values['asset_image']) ? $values['asset_image'][0] : $values['asset_image'];

            if ($file = file_load($fid)) {
                // Make the file permanent
                $file->status = FILE_STATUS_PERMANENT;
                file_save($file);

                $lang = LANGUAGE_NONE;

                $entity->field_custom_asset_image[$lang][0] = array(
                    'fid' => $values['asset_image'],
                    'display' => 1,
                    'description' => '',
                );

                // Critical: Record that this entity is using this file
                file_usage_add($file, 'asset', 'asset', $fid);
            }
        }
        assetController()->saveAsset($entity);
        drupal_set_message(t('Asset %name saved.', array('%name' => $entity->name)));
    }
}

function asset_delete($id)
{
    assetController()->deleteAsset($id);
    drupal_set_message('Asset deleted.');
    drupal_goto('asset');
}

function asset_view($id)
{
    $assetEntity = assetController()->loadAssetByID($id);
    $wrappedAsset = assetEntityWrapper($assetEntity);
    drupal_add_css(drupal_get_path('module', 'asset') . '/css/asset-view.css');
    return [
        '#theme' => 'asset_view',
        '#asset' => $wrappedAsset,
    ];
}


//Theme hook
function asset_theme($existing, $type, $theme, $path)
{
    return array(
        'asset_list' => array(
            'variables' => array(
                'header' => NULL,
                'rows' => NULL,
                'pager' => NULL,
                'empty' => NULL,
                'filter_form' => NULL,
            ),
            'template' => 'asset-list',
            'path' => drupal_get_path('module', 'asset') . '/templates',
        ),
        'asset_view' => array(
            'variables' => array(
                'asset' => NULL,
            ),
            'template' => 'asset-view',
            'path' => drupal_get_path('module', 'asset') . '/templates',
        ),
        'asset_form_template' => array(
            'render element' => 'form',
            'template' => 'asset-form',
            'path' => drupal_get_path('module', 'asset') . '/templates',
        ),
    );
}


function asset_maintenance($id)
{
//    add item to queue
    $queue = DrupalQueue::get('asset_maintenance_queue');
    $queue->createItem(array('asset_id' => $id));
}

/**
 * Implements hook_cron_queue_info().
 */
function asset_cron_queue_info()
{
    $queues['asset_maintenance_queue'] = array(
        'worker callback' => 'asset_asset_maintenance_worker', // The function that does the work
        'time' => 60, // Max number of seconds to spend processing this queue during cron
    );
    return $queues;
}

function asset_asset_maintenance_worker($data)
{
    $asset_id = $data['asset_id'];

    $values = array(
        'type' => 'maintenance',
        'created' => REQUEST_TIME,
        'changed' => REQUEST_TIME,
    );

    $maintenance = entity_create('maintenance', $values);

//    using wrapper for lazy laoding

    $m_wrapper = entity_metadata_wrapper('maintenance', $maintenance);
    $m_wrapper->field_custom_maintenance_asset->set($asset_id);

    $taxonomy_options = asset_get_taxonomy_options('status');
    $term_id = array_search('Waiting', $taxonomy_options);
    if ($term_id) {
        $m_wrapper->field_custom_maintenance_status->set($term_id);
    }
    $m_wrapper->save();

//    finding manager and setting up area dor mail
    $asset_wrapper = entity_metadata_wrapper('asset', $asset_id);
    $organization_wrapper = $asset_wrapper->field_custom_asset_organization;

    $manager_email = '';
    if ($organization_wrapper->value()) {
        $user_wrapper = $organization_wrapper->field_custom_manager;
        if ($user_wrapper->value()) {
            $manager_email = $user_wrapper->mail;
        }

        $owner_email = 'abhayanepal.47@gmail.com';

        $params = array(
            'asset' => $asset_wrapper->value(),
            'maintenance' => $m_wrapper->value(),
        );
        $language = language_default();

        // Send Mail to Owner
        if (!empty($owner_email)) {
            drupal_mail('asset', 'maintenance_req_owner', $owner_email, $language, $params);
        }

        // Send Mail to Manager
        if (!empty($manager_email)) {
            drupal_mail('asset', 'maintenance_req_manager', $manager_email, $language, $params);
        }
    }
}

/**
 * Implements hook_mail().
 */
function asset_mail($key, &$message, $params)
{
    $asset = $params['asset'];
    switch ($key) {
        case 'maintenance_req_owner':
            $message['subject'] = t('Maintenance Request for', array('!name' => $asset->title));
            $message['body'][] = t('A maintenance request has been initiated for your asset.', array('!title' => $asset->title));
            break;

        case 'maintenance_req_manager':
            $message['subject'] = t('Maintenance Request Sent - Wait');
            $message['body'][] = t('A maintenance request has been sent for an asset. Please wait for further updates.', array('!title' => $asset->title));
            break;
    }
}
